name: Github Action Test 실행
on:
  pull_request:
    branches:
      - main
      - develop
      - stage
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 의존성 설치
        run: npm ci

      - name: 테스트 실행하기
        run: npm run test
